controller_manager:
  ros__parameters:
    update_rate: 30  # Частота обновления контроллера (Гц)
    use_sim_time: true  # Использование симуляционного времени

    # Контроллер для дифференциального привода
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    # Контроллер для публикации состояний суставов
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
 
# Параметры для контроллера дифференциального привода
diff_cont:
  ros__parameters:
    publish_rate: 50.0  # Частота публикации данных (Гц)
    odom_frame_id: odom
    base_frame_id: root_link  # Фрейм базы робота
    left_wheel_names: ["base_to_l_f_wheel", "base_to_l_m_wheel", "base_to_l_r_wheel"]
    right_wheel_names: ["base_to_r_f_wheel", "base_to_r_m_wheel", "base_to_r_r_wheel"]
    wheel_separation: 0.8  # Расстояние между колесами (м)
    wheel_radius: 0.19  # Радиус колес (м)
    use_stamped_vel: false  # Использование stamped velocity (со временем)
    wheels_per_side: 3
    # Дополнительные параметры (раскомментируйте, если нужно)
    # odom_frame_id: odom  # Фрейм одометрии
    # enable_odom_tf: true  # Включение публикации TF для одометрии
    # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]  # Ковариация позиции
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]  # Ковариация скорости
    # open_loop: true  # Открытый цикл управления
    # cmd_vel_timeout: 0.5  # Таймаут команд (сек)
    # publish_limited_velocity: true  # Публикация ограниченной скорости
    # velocity_rolling_window_size: 10  # Размер окна для расчета скорости