map_server:
  ros__parameters:
    yaml_filename: "~/map.yaml"

amcl:
  ros__parameters:
    initial_pose:
      x: 0.0
      y: 0.0
      theta: 0.0

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    
    controller_plugins: ["FollowPath"]
    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_velocity: 0.5
      max_linear_velocity: 0.8
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      transform_tolerance: 0.1
      
      # Критики для оценки пути
      critics: ["GoalAngle", "PathAlign", "PreferForward", "Obstacle"]
      GoalAngle.scale: 2.0
      PathAlign.scale: 2.0
      PreferForward.scale: 1.0
      Obstacle.scale: 1.0

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]