<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

<!--collision contact_coefficients in gazebo-->

  <xacro:macro name="box_inertia" params="b_mass b_length b_width b_height">
    <inertial>
      <mass value="${b_mass}"/>
      <inertia ixx="${b_mass*(b_length*b_length+b_height*b_height)/12}" ixy="0.0" ixz="0.0"
               iyy="${b_mass*(b_width*b_width+b_height*b_height)/12}" iyz="0.0"
               izz="${b_mass*(b_length*b_length+b_width*b_width)/12}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="c_mass c_radius c_height">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${c_mass}"/>
      <inertia ixx="${c_mass*(3*c_radius*c_radius+c_height*c_height)/12}" ixy="0.0" ixz="0.0"
               izz="${c_mass*(3*c_radius*c_radius+c_height*c_height)/12}" iyz="0.0"
               iyy="${c_mass*c_radius*c_radius/2}"/>
    </inertial>
  </xacro:macro>

  <xacro:property name="base_link_mass" value="103.5" /><!-- please correct this -->
  <xacro:property name="base_link_length" value="0.9" />
  <xacro:property name="base_link_width" value="0.37" />
  <xacro:property name="base_link_height" value="0.40" />
  <xacro:property name="ctrlbox_link_mass" value="0.23" /><!-- please correct this -->
  <xacro:property name="ctrlbox_link_length" value="0.045" />
  <xacro:property name="ctrlbox_link_width" value="0.25" />
  <xacro:property name="ctrlbox_link_height" value="0.25" />
  <xacro:property name="visionbox_link_mass" value="0.01" />
  <xacro:property name="visionbox_link_length" value="0.14" />
  <xacro:property name="visionbox_link_width" value="0.20" />
  <xacro:property name="visionbox_link_height" value="0.015" />
  <xacro:property name="wheel_mass" value="20.0" /><!-- please correct this -->
  <xacro:property name="wheel_radius" value="0.19" /><!-- please correct this -->
  <xacro:property name="wheel_height" value="0.15" /><!-- please correct this -->
  <xacro:property name="wheelbase" value="1.0" /><!-- please correct this -->
  <xacro:property name="track" value="0.8" />
  <xacro:property name="clearance" value="0.2" />
  <xacro:property name="wheel_vertical_offset" value="0.03282"/>

  <xacro:arg name="laser_rotation" default="false"/>

  <link name="root_link">
  </link>

      <!-- BASE_FOOTPRINT LINK -->

    <joint name="root_footprint_joint" type="fixed">
        <parent link="root_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

  <joint name="base_to_root" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_link_height/2+clearance}" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="base_link_geometry">
    <geometry>
      <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find real_rover)/meshes/base.stl"/>
      </geometry>
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />
    </visual>
    <collision>
      <xacro:base_link_geometry />
    </collision>
    <xacro:box_inertia
     b_mass="${base_link_mass}"
     b_length="${base_link_width}"
     b_width="${base_link_length}"
     b_height="${base_link_height}"/>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/RustySteel</material>
  </gazebo>

  <joint name="ctrlbox_to_base" type="fixed">
    <parent link="base_link"/>
    <child link="ctrlbox_link"/>
    <origin xyz="${base_link_length/2+ctrlbox_link_length/2+0.15} 0 ${ctrlbox_link_height/2+0.035-base_link_height/2}" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="ctrlbox_link_geometry">
    <geometry>
      <box size="${ctrlbox_link_length} ${ctrlbox_link_width} ${ctrlbox_link_height}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:macro>

  <link name="ctrlbox_link">
    <visual>
      <xacro:ctrlbox_link_geometry />
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>
    <collision>
      <xacro:ctrlbox_link_geometry />
    </collision>
    <xacro:box_inertia
     b_mass="${ctrlbox_link_mass}"
     b_length="${ctrlbox_link_length}"
     b_width="${ctrlbox_link_width}"
     b_height="${ctrlbox_link_height}"/>
  </link>
  <gazebo reference="ctrlbox_link">
    <material>Gazebo/RustySteel</material>
  </gazebo>

  <xacro:macro name="visionbox_link_geometry">
        <geometry>
          <box size="${visionbox_link_length} ${visionbox_link_width} ${visionbox_link_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:macro>

  <link name="visionbox_link">
    <visual>
      <xacro:visionbox_link_geometry />
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>
    <collision>
      <xacro:visionbox_link_geometry />
    </collision>
    <xacro:box_inertia
     b_mass="${visionbox_link_mass}"
     b_length="${visionbox_link_length}"
     b_width="${visionbox_link_width}"
     b_height="${visionbox_link_height}"/>
  </link>
  <gazebo reference="visionbox_link">
    <material>Gazebo/RustySteel</material>
  </gazebo>

  <joint name="visionbox_to_ctrlbox" type="fixed">
    <parent link="ctrlbox_link"/>
    <child link="visionbox_link"/>
    <origin xyz="${visionbox_link_length/2 - ctrlbox_link_length/2}
		            0
		            ${ctrlbox_link_height/2+visionbox_link_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="front_camera_link"></link>
  
  <!--xacro:sensor_d415 parent="front_camera_link" use_nominal_extrinsics="true" add_plug="false">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_d415-->

  <joint name="ctrlbox_to_camera_link" type="fixed">
    <parent link="ctrlbox_link"/>
    <child link="front_camera_link"/>
    <origin xyz="${ctrlbox_link_length/2} 0.0 0.026" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="wheel_joint" params="w_name origin_x origin_y origin_z geometry_yaw mu1 mu2">
    <link name="${w_name}_wheel">
      <visual>
        <geometry>
          <mesh filename="file://$(find real_rover)/meshes/wheel.stl"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2+geometry_yaw}"/>
        <material name="black">
          <color rgba="0.2 0.2 0.2 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <xacro:cylinder_inertia
        c_mass="${wheel_mass}"
        c_radius="${wheel_radius}"
        c_height="${wheel_height}"/>
    </link>

    <joint name="base_to_${w_name}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${w_name}_wheel"/>
      <axis xyz="0 1 0"/>
      <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>

    </joint>

    <gazebo reference="${w_name}_wheel">
      <mu1 value="${mu1}"/>
      <mu2 value="${mu2}"/>
      <fdir1 value="0 0 0"/>

      <!--kp value="10000000.00" />
      <kd value="1.00" />
      <minDepth value="0.001"/-->

      <maxContacts value="1"/>
      <turnGravityOff>false</turnGravityOff>
      <material>Gazebo/DarkGrey</material>
    </gazebo>

  </xacro:macro>

  <xacro:wheel_joint
    w_name="l_f"
    origin_y="${track/2}"
    origin_x="${wheelbase/2}"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="0"
    mu1="0.5"
    mu2="0.5"/>

  <xacro:wheel_joint
    w_name="l_m"
    origin_y="${track/2}"
    origin_x="0"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="0"
    mu1="0.5"
    mu2="0.5"/>

  <xacro:wheel_joint
    w_name="l_r"
    origin_y="${track/2}"
    origin_x="${-wheelbase/2}"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="0"
    mu1="0.5"
    mu2="0.5"/>

  <xacro:wheel_joint
    w_name="r_f"
    origin_y="${-track/2}"
    origin_x="${wheelbase/2}"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="${pi}"
    mu1="0.5"
    mu2="0.5"/>

  <xacro:wheel_joint
    w_name="r_m"
    origin_y="${-track/2}"
    origin_x="0"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="${pi}"
    mu1="0.5"
    mu2="0.5"/>
    
  <xacro:wheel_joint
    w_name="r_r"
    origin_y="${-track/2}"
    origin_x="${-wheelbase/2}"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="${pi}"
    mu1="0.5"
    mu2="0.5"/>

  <!-- GPS -->
  <link name="gps_link"></link>

  <joint name="gps_joint" type="fixed">
    <parent link="ctrlbox_link"/>
    <child link="gps_link"/>
    <origin xyz="0 -0.1 0.105" rpy="0 0 0"/>
  </joint>

</robot>